name: Build with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: MidnightControls-Artifacts
          path: /build/libs/
